#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** FPU USAGE in KERNEL TASKs ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter>, <ctrl-C> to end it."
read junk
sync
insmod ./fp.o
./display
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
