#!/bin/sh

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** INTERTASK MSG BASED DIGITAL CLOCK (kernel/mup) ***"
echo "Press <enter> to load modules:"
read junk
cd ../..; ./ldmod; cd -
echo
echo "Now start the mup msg clock <enter>."
read junk
sync
insmod ./dispclk.o
insmod ./cmdclk.o
insmod ./cmdcrn.o
insmod ./clock.o
./keybrd
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
