#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo

trao "./rem" INT HUP TERM ALARM

echo "*** RELEASING TASKs WAITING ON MBXES (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
sync
echo
echo "Now start the realtime process <enter> and wait for its end."
read junk
sync
insmod ./mbxdel.ko
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
