#!/bin/sh

prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

libpath=`rtai-config --library-dir`
export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH
 
MODULES=$prefix/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** A TASKLET BASED USER SPACE INTERRUPT HANDLER ***"
echo "Press <enter> to load modules:"
read junk
cd ../..; ./ldmod; cd -
insmod $MODULES/rtai_tasklets.o
insmod $MODULES/rtai_usi.o
echo
echo "Now start the realtime tasklet <enter>."
read junk
sync
$SUDO ./usi_tasklet
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
