#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** PRIORITY INHERITANCE CHECK FOR RTAI RES-SEM (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter> and wait for its end."
read junk
sync
insmod ./res-mtx_sem.ko
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
