#!/bin/sh

prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

sync
insmod $MODULES/rtai_hal.o
sync
insmod $MODULES/rtai_lxrt.o
sync
insmod $MODULES/rtai_sem.o
sync
insmod $MODULES/rtai_mbx.o
sync
insmod $MODULES/rtai_msg.o
sync
insmod $MODULES/rtai_fifos.o
sync
insmod $MODULES/rtai_tbx.o
sync
insmod $MODULES/rtai_bits.o
sync
insmod $MODULES/rtai_mq.o
sync
insmod $MODULES/rtai_shm.o
sync
