TARGETS = \
	bitstest \
	forcesoft \
	forked \
	hardsoftsw \
	heaps \
	intertaskmsg \
	latency \
	master_slave \
	msg_clock \
	netrpc \
	pqueue \
	preempt \
	rt_agent \
	sem_clock \
	linux_server \
	tasklets \
	tbx \
	threaded

include ../share/recurse.mk
