#!/bin/sh

prefix=`rtai-config --prefix`

if test "$prefix" = ""; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

libpath=`rtai-config --library-dir`
export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

MODULES=$prefix/modules

trap "./rem" INT iHUP TERM

echo
echo "*** TESTING ASYNC REMOTE CALLs (user) ***"
echo "Press <enter> to load modules:"
read junk
cd ../..; ./ldmod; cd -
sync
insmod $MODULES/rtai_netrpc.ko ThisNode="127.0.0.1";
echo
echo "Now start the realtime process <enter>,"
echo "Press <enter> when you want to end it."
read junk
./receiver $10 SndNode="127.0.0.1" &
./sender RcvNode="127.0.0.1"
while(`ps -a | grep -q receiver`); do sleep 1; done
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
