#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo

trap "./rem" INT TERM HUP ALARM

echo "*** MBXes on SPACE DEFICIENT BUFFERs (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
sync
echo
echo "Now start the realtime process <enter> and wait for its end."
read junk
sync
insmod ./mbx.ko;
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
