#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo

trap "./rem" INT TERM HUP ALARM

echo "*** PREEMPTION TEST (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime the fifo based fast ticking <enter>,"
echo "<ctrl-C> to end it:>"
read junk
sync
insmod ./preempt.ko;
./display
sync
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
