#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** DIRECT IRQ HANDLING (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ../..; ./ldmod; cd -
sync
echo
echo "Now start the realtime process <enter> and wait for its end."
read junk
sync
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod ./dsp_rt.ko;
else insmod ./dsp.o; fi
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
