#!/bin/sh

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** LATENCY MEASUREMENT (user) ***"
echo "Press <enter> to load LXRT modules ..."
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process, <enter> twice to end them all"
read junk
$SUDO ./latwdisp &
sleep 1
$SUDO ./display &
read junk
read junk
DISP=`ps -a |grep display | awk '{ print $1 }'`
kill -9 $DISP
LATE=`ps -a |grep latwdisp | awk '{ print $1 }'`
kill -9 $LATE
../remod
