#!/bin/sh

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

trap "./rem" INT TERM HUP ALARM

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** Simple RTAI SHM demo (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter>, <ctrl-C> to end it."
read junk
sync
insmod ./shm.ko
./display
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
