#!/bin/sh
prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

libpath=`rtai-config --library-dir`

if test "$libpath" = ""; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

trap "./rem" INT KILL TERM

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** HEARTBEAT (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ../..; ./ldmod; cd -
sync
echo
echo "Now start the realtime process <enter> and wait for its end."
read junk
sync
insmod $MODULES/rtai_rtdm.ko
insmod ./rtdmtest.ko;
sleep .5
./rtdm

echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
