#!/bin/sh
prefix=`rtai-config --prefix`

if test "$prefix" = ""; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

trap "./rem" INT TERM HUP ALARM 

echo
echo "*** A METTLEY OF LATENCY MEASUREMENTs (user, kernel, kernel timers) ***"
echo "Press <enter> to load modules:"
read junk
cd ../..; ./ldmod; cd -
insmod $MODULES/rtai_rtdm.ko; insmod ./timerbench.ko
sync
echo
echo "Now start your realtime test of choice <enter>,"
echo "<ctrl-C> to end it:>"
read junk
./latency -p 40 -t $1
sync
echo
echo "Done. Press <enter> to remove the modules."
read junk
