#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** ROUND ROBIN SCHEDULING (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter>:"
read junk
sync
insmod ./rndrob.o
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
