#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** FAST TICKING USING FIFOs (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime the fifo based fast ticking <enter>,"
echo "<ctrl-C> to end it:>"
read junk
sync
insmod ./fastick1.o
./display
sync
rmmod fastick1
echo "*** FAST TICKING USING SYSREQs (kernel) ***"
echo "Now start the realtime the sysreq based fast ticking <enter>,"
echo "<ctrl-C> to end it:>"
read junk
sync
insmod ./fastick2.o
./display
sync
rmmod fastick2
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
