#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** TYPED MBXes 1 (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter> and wait for its end."
read junk
sync
insmod ./tbx1.o
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
