#!/bin/sh
trap "./rem" INT TERM HUP ALARM

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** SOUND USING FIFOs (user) ***"
echo "Press <enter> to load modules:"
read junk
cd ../..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter>, <ctrl-C> to end it."
read junk
sync
insmod ./speaker.ko;
./player
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
