#!/bin/sh

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** COMEDI INSTRUCTION LIST TEST (user) ***"
echo "Press <enter> to load LXRT modules:"
read junk
cd ../; ./ldmod; cd -
/sbin/modprobe ni_pcimio
/sbin/modprobe kcomedilib
/sbin/insmod /usr/realtime/modules/rtai_comedi.ko
/usr/local/sbin/comedi_config /dev/comedi1 ni_pcimio
/usr/local/bin/comedi_calibrate -f /dev/comedi1
echo
echo "Now start the realtime process <enter>:"
read junk
$SUDO ./insn
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
