#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** TESTs CONDVARs and BARRIERs (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime process <enter> and wait for its end:"
read junk
insmod ./condtest.o
echo
echo "Done. Press <enter> to remove the modules."
read junk
rmmod condtest
./rem
