#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** TESTs RWLOCKs (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..
./ldmod
cd -
sync
echo "Now start the realtime process <enter>."
read junk
insmod ./rwlocks.o
echo
echo "Done. Press <enter> to remove the modules."
read junk
rmmod rwlocks
./rem
