#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** LATENCY MEASUREMENT (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start the realtime the fifo based fast ticking <enter>,"
echo "<ctrl-C> to end it:>"
read junk
sync
insmod ./latency_rt.o
./display
sync
rmmod latency_rt
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
