#!/bin/sh

prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** SIMPLE WD CHECK (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
insmod $MODULES/rtai_wd.ko
echo
echo "Now start the realtime process <enter>:"
read junk
sync
insmod ./wd.ko
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
