#!/bin/sh
prefix=`rtai-config --prefix`

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** A METTLEY OF LATENCY MEASUREMENTs (user, kernel, kernel timers) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; ./ldmod; cd -
echo
echo "Now start your realtime test of choice <enter>,"
echo "<ctrl-C> to end it:>"
read junk
sync
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod $MODULES/rtai_tasklets.ko;
else insmod $MODULES/rtai_tasklets.o; fi
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod $MODULES/rtai_rtdm.ko; insmod ./timerbench_rt.ko
else insmod $MODULES/rtai_rtdm.o; insmod ./timerbench_rt.o; fi
./latency -t $1
sync
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
