#!/bin/sh

prefix=`rtai-config --prefix`
arch=`rtai-config --arch`
insmod=/sbin/insmod

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** RTAI PROPER SYSREQs (kernel) ***"
echo "Press <enter> to load modules:"
read junk
echo
echo "Now start the realtime process <enter>, <ctrl-C> to end it."
read junk
insmod $MODULES/rtai_hal.ko
sync
if (`rtai-config --linux-version | grep -q 2.6`);
then insmod ./sysreq_rt.ko;
else insmod ./sysreq_rt.o; fi
./display
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
