#!/bin/sh

prefix=`rtai-config --prefix`
arch=`rtai-config --arch`
insmod=/sbin/insmod

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

trap "./rem" INT TERM HUP ALARM

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** RTAI PROPER SYSREQs (kernel) ***"
echo "Press <enter> to load modules:"
read junk
echo
echo "Now start the realtime process <enter>, <ctrl-C> to end it."
read junk
sync
insmod $MODULES/rtai_hal.ko; 
insmod ./sysreq.ko;
./display
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
