TARGETS = \
	bitstest \
	condtest \
	edf \
	fastick \
	fp \
	i386 \
	latency \
	mbx \
	mbx_del \
	msg_clock \
	mupspecific \
	namedstuff \
	netrpc \
	pqueue \
	preempt \
	prioinher \
	res-mtx_sem \
	rndrob \
	rwlocks \
	sem_clock \
	shm \
	splocks \
	sysreq \
	tasklets \
	tbx

include ../share/recurse.mk
